### PR TITLE
py_contours_begin.rst: findContours() doesn't return image

### PR DESCRIPTION
**Pull request by dequis**
Found this little inaccuracy, I'm not sure if this was ever part of the API.

### CODE REVIEW

**Comment by abidrahmank** [comment]
Yes you are right, thank you... First few tutorials were written as per OpenCV2.4. Later it was decided to shift to OpenCV3 since it is going to be the major version within a couple of months.

But I forgot to change those small corrections. Such corrections are there in some more functions. Those functions are here : https://github.com/Itseez/opencv/commit/e75df5631775dc512fba2d9c41598041c8beedaa

If you can correct such mistakes in other tutorials also, it would be great...

**Comment by abidrahmank** [comment]
Oops... sorry... you did the reverse... I had already corrected it. ...

Let me get it straight.. I hope you are using OpenCV 2.4.x. These tutorials are created for OpenCV 3.x. In version 3, there are slight changes in API of some functions. You need to build OpenCV master branch from git to get these APIs. 

Please comment if any further questions.

**Comment by dequis** [comment]
Oh damn, sorry, wasn't even aware that 3.x was a thing. Yeah, I'm using 2.4. Are the 3.x changes interesting enough to make it worth building from master? 

Also, closing this PR.

**Comment by abidrahmank** [comment]
Regarding Python, in V3, old `cv` module is completely removed. Dependancy on C API will be minimum (trying to be zero). C++ will be the main API. It will be a LTS version, ie supported for a long time. There is likely to have support for python 3. 

Actually main developments are in field of GPU (CUDA, OpenCL) and ARM (android) etc. Anyway it is good, many new modules and functionalities are getting implemented. Even I myself added many python bindings for several functions, but all are pushed to V3.

**Comment by dequis** [comment]
Got it, thanks! And also thanks for the wonderful docs - they are a really efficient way to get used to the cv2 api.

**Comment by abidrahmank** [comment]
Thank you... Always feel free to correct all mistakes you see... It will be
highly appreciated...

Abid K.

**Pull request closed without merging**
